column "custom_thumbnail" does not exist
 bad query: ALTER TABLE "dms_file" RENAME "custom_thumbnail" TO "openupgrade_legacy_14_0_custom_thumbnail"
ERROR: column "custom_thumbnail" does not exist